/* Generated by Together */

#ifndef GDDCONE_H
#define GDDCONE_H
#include "detModel/Sections/GDDshape.h"
class GDDcone :public GDDshape {
    private:
        double RIn1;///default 0
        double ROut1;///default 0
        double RIn2;///default 0
        double ROut2;///default 0
        double Z;///default 0
        double PhiBeg;///default 0
        double PhiEnd;///default 360
 };
#endif //GDDCONE_H
