/* Generated by Together */

#ifndef GDDDERCATEGORY_H
#define GDDDERCATEGORY_H

#include<vector.h>
#include<string.h>

class GDDconst;
/**
 * @author D.Favretto & R.Giannitrapani 
 */
class GDDconstCategory {
 public:

  GDDconstCategory():categoryName(""),overview(""){;} 
  ~GDDconstCategory();//use purge

  void setCategoryName(string name){categoryName=name;}
  string getCategoryName()const{return categoryName;}

  void setOverview(string poverview){overview=poverview;}
  string getOverview()const{return overview;}

  void addConstant(GDDconst* c){consts.push_back(c);}
  int getConstantNumber()const{return consts.size();}  
  vector<GDDconst*>getConsts()const{return consts;}

 private:
  string categoryName;
  string overview;
  /** @link aggregation */
  vector < GDDconst * > consts;
};
#endif //GDDDERCATEGORY_H
