/* Generated by Together */

#ifndef GDDDERCATEGORY_H
#define GDDDERCATEGORY_H

/**
 * @author D.Favretto & R.Giannitrapani 
 */
class GDDderCategory {
private:

    /** @link aggregation */
    vector < GDDconst * > consts;
};
#endif //GDDDERCATEGORY_H