/* Generated by Together */

#ifndef GDDPRIMCATEGORY_H
#define GDDPRIMCATEGORY_H

/**
 * @author D.Favretto & R.Giannitrapani 
 */
class GDDprimCategory {
private:    

    /** @link aggregation */
    vector < GDDprim * > prims;
};
#endif //GDDPRIMCATEGORY_H